### ISSUE TITLE
Falses

### ISSUE THREAD

**Issue by Martin1918** [undersquire/Hades#14]
Hi,  when you walk on snow you flag some checks, when you ride a horse you flag some check, when you sneak and right click on horse you flag some checks and when you die and respawn you flag some checks

**Comment by undersquire** [comment]
Thanks for reporting these issues! However, I would greatly appreciate if you specified which specific checks falsed? I will test this and fix the issues!

**Comment by Martin1918** [comment]
I make you 3 videos:
https://gyazo.com/ae8cab2e00d39585e68a90fe40b6a8dc
https://gyazo.com/e3c37974b721fcf5ccf662c5e816dfbe
https://gyazo.com/87c1373d1501ab6e3eb18258b7a4f5fd

**Comment by Martin1918** [comment]
Oh I found two  other bugs:
https://gyazo.com/9989956aa1e4e3c4eab5ba72d698bf3a
https://gyazo.com/c2dbb64aded11867afd14c01a348c5c2

**Comment by undersquire** [comment]
Thank you for making videos! I will patch these bugs soon!

**Comment by Tecnio** [comment]
Yes, I am now currently working on some of these falses.
