### ISSUE TITLE
Other things

### ISSUE THREAD

**Issue by Martin1918** [undersquire/Hades#21]
Reach check false a lot:
https://gyazo.com/74963b71c6601ecd4715b9fa94924433

When you speed hack you can get tp below blocks:
https://gyazo.com/e39d2be5b9c5c5c581ad7673785282ac

When you hit a player but he his in creative he flags:
https://gyazo.com/d53ff7a6d8f1d0fba109596ff0124840

An other bug with velocity:
https://gyazo.com/e080a82defdfaac0debd94e236c89b24

**Comment by Tecnio** [comment]
I have fixed your issues thank you for reporting!
