### ISSUE TITLE
Scaffold A false

### ISSUE THREAD

**Issue by Martin1918** [undersquire/Hades#24]
**Describe the bug**
When I right click with anything in my hands I flag Scaffold A

**Screenshots**
https://gyazo.com/2ff08367c2ccc7491c230a58ca974451

**Server Version:**
1.8

**Plugin Version:**
Latest version of Hades

**Comment by Tecnio** [comment]
Thank you for reporting this issue! I was unable to re-create the issue but i will keep this open.

**Comment by undersquire** [comment]
Removed that check in recode.
