### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by Martin1918** [undersquire/Hades#25]
**Describe the bug**
There are errors when a player joins my server or goes to the multiplayer menu

**Screenshots**
https://gyazo.com/edf92ae288d6e4ef6f7ce2ad9e31ec4f
https://pastebin.com/izTLapKT

**Server Version:**
1.8

**Plugin Version:**
Latest Hades version

**Comment by Tecnio** [comment]
Thank you for reporting this issue! This issue is not related to the anticheat because its caused by packetevents.

**Comment by GladUrBad** [comment]
Luna uses packetevents hope this gets fixed soon
