### ISSUE TITLE
Join Error

### ISSUE THREAD

**Issue by Martin1918** [undersquire/Hades#26]
I heard that you are using a custom version of TinyProtocol so this is why I send you that.

When I join my server there is this error:
https://pastebin.com/6qSvp9Ba

**Server Version:**
1.8

**Plugin Version:**
Latest Hades Version

**Comment by Tecnio** [comment]
Sorry for the inconvenience! We have currently switched back to PacketEvents because of some reasons. We currently don’t have time to fix the join issue, but to fix the issue is in our todo list! Thank you for reporting!
