### ISSUE TITLE
Doesnt Work on mSpigot?

### ISSUE THREAD

**Issue by rbuh** [undersquire/Hades#27]
**Describe the bug**
A clear and concise description of what the bug is. Just errors on mspigot

**To Reproduce**
Steps to reproduce the behavior: use mSpigot

**Expected behavior**
A clear and concise description of what you expected to happen. noting works

**Screenshots**
If applicable, add screenshots to help explain your problem. nope

**Server Version:** mSpigot 1.7.10

**Plugin Version:** latest

**Additional context**
Add any other context about the problem here. nope

**Comment by undersquire** [comment]
Thank you for reporting this issue! We will look into fixing this issue, however please note that we provide limited support for forks of Spigot due to the differences in how things are handled in some Spigot forks. However, we will still look into your issue and attempt to fix the issue.

**Comment by Tecnio** [comment]
We do not have mSpigot and without mSpigot we can’t fix this issue. So I am going to close this issue because we do not plan on buying it.
