### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Martin1918** [undersquire/Hades#28]
These errors sometimes appear when a player joins / disconnects
After the error with "asynchronus entity world" appeared the chunk was delete

**Screenshots**
https://gyazo.com/79219735575c854177e13ae196f1ae07
https://gyazo.com/55035c377cae632c07248eb52f9e17e5
https://gyazo.com/01644ea1accd81caf0dc28a55af1b82c
https://gyazo.com/8bd22d1d825dff12c06f30fbb0778863

**Server Version:**
1.8.8

**Plugin Version:**
Latest Hades

**Comment by Smakina** [comment]
Please do not use "latest Hades" since this issue could have been read after updates.

**Comment by undersquire** [comment]
Is this error the latest Hades on spigot? Or the latest commit here on github?

**Comment by Martin1918** [comment]
It's from the latest commit on github

**Comment by Numzskull** [comment]
Will be resolving the issue

**Comment by retrooper** [comment]
Latest version of packetevents(api hades uses for packets) fixed such issues.
Please use the latest version of Hades!
