### ISSUE TITLE
Reach check is broken

### ISSUE THREAD

**Issue by Martin1918** [undersquire/Hades#30]
**Describe the bug**
Reach check is totaly broken

**To Reproduce**
Just attack an entity like villager

**Screenshots**
https://gyazo.com/dd8cc48aa55d468b5a6e845734085cdb

**Server Version:**
1.8.8

**Plugin Version:**
Latest Hades

**Comment by Tecnio** [comment]
Known issue. Closing issue. (Do Not Say Latest Hades)
